export const FIELD = {
  EMP_NO: 'emp_no',
  CORP_CODE: 'corp_code',
  BUSI_PLACE: 'busi_place',
  TASK: 'task',
  EMP_NAME: 'emp_name',
  UNIT_WORK_NO: 'unit_work_no',
  PLANT_CODE: 'plant_code',
  EQUIP_CODE: 'equip_code',
  UNIT_WORK_CODE: 'unit_work_code',
  TEL_NO: 'tel_no',
  MOBILE_NO: 'mobile_no',
  EMAIL: 'email',
  ENT_DATE: 'ent_date',
  BIRTHDAY: 'birthday',
  BIRTHDAY_TYPE: 'birthday_type',
  GENDER: 'gender',
  RESPONSI: 'responsi',
  ON_WORK_YN: 'on_work_yn',
  USER_ID: 'user_id',
  ROW_STAT: 'row_stat',
};
