name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 추가사항"
    labels:
      - "enhancement"
      - "feature"
  - title: "개선 및 변경사항"
    labels:
      - "improve"
  - title: "🐛 버그픽스"
    labels:
      - "bugfix"
      - "fix"
  - title: "🧰 문서/기타 설정"
    labels:
      - "etc"
      - "chore"
      - "documentation"
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
exclude-labels:
  - "nochangelog"
  - "skip-changelog"

template: |
  ## 릴리즈 노트
  $CHANGES
