version: "3.7"
services:
  nginx:
    container_name: wdk-client-qucistarter
    image: ghcr.io/vntgcorp/wdk-client-qucistarter:latest
    ports:
      # host:container
      - "80:80"
    # volumes:
      # 직접 입력할 경우 - local(host):container
      #- ./docker/nginx/Development:/etc/nginx/conf.d
      # Django의 static 경로를 매핑하고자하는 nginx 경로 - 운영일때는 경로 바꿔야 함
      # - static_volume:/usr/src/app/staticfiles
    environment:
      - TZ=Asia/Seoul
    # depends_on:
    #   - backend
    restart: unless-stopped
